FROM node
WORKDIR /app
COPY rldb/package.json .
COPY rldb rldb
ENV NPM_CONFIG_LOGLEVEL warn
ENV PATH /app/node_modules/.bin:$PATH
RUN npm install
WORKDIR /app/rldb
EXPOSE 3000
CMD CHOKIDAR_USEPOLLING=true npm start