FORMAT: 1A
HOST: http://docs.janabimustafa.apiary.io/

# RocketLeagueDB API

Rocket League Database (RLDB) is an API allowing players and fans to obtain information about in-game items and top players.

## Paints [/paints/]
### Get all Paints [GET]

+ Response 200 (application/json)

        [{
            "id": 0,
            "name": "Circuit Board",
            "type": "paint",
            "rarity": "rare",
            "source": "crate",
            "crate": 0,
            "release_date": "2017-07-05",
            "decals": [1, 2, 3, 4, 5]
        }]

## Paint [/paints/{name}]
### Get a Paint Finish by name [GET]

+ Response 200 (application/json)

        {
            "id": 0,
            "name": "Circuit Board",
            "type": "paint",
            "rarity": "rare",
            "source": "crate",
            "crate": 0,
            "release_date": "2017-07-05",
            "decals": [1, 2, 3, 4, 5]
        }

## Paint [/paints/{id}]
### Get a Paint Finish by id [GET]

+ Response 200 (application/json)

        {
            "id": 0,
            "name": "Circuit Board",
            "type": "paint",
            "rarity": "rare",
            "source": "crate",
            "crate": 0,
            "release_date": "2017-07-05",
            "decals": [1, 2, 3, 4, 5]
        }


## Bodies [/bodies/]
### Get all bodies [GET]

+ Response 200 (application/json)

        [{
            "id": 0,
            "name": "Backfire",
            "type": "body",
            "rarity": "common",
            "source": "body",
            "release_date": "2015-07-07",
            "decals": [1, 2, 3, 4, 5]
        },]
        
## Body [/bodies/{name}]
### Get a Body by name [GET]

+ Response 200 (application/json)

        {
            "id": 0,
            "name": "Backfire",
            "type": "body",
            "rarity": "common",
            "source": "body",
            "release_date": "2015-07-07",
            "decals": [1, 2, 3, 4, 5]
        }
## Body [/bodies/{id}]
### Get a Body by id [GET]

+ Response 200 (application/json)

        {
            "id": 0,
            "name": "Backfire",
            "type": "body",
            "rarity": "common",
            "source": "body",
            "release_date": "2015-07-07",
            "decals": [1, 2, 3, 4, 5]
        }

## Decals [/decals/]
### Get all Decals [GET]

+ Response 200 (application/json)

        [{
            "id": 0,
            "name": "Funny Book",
            "type": "decal",
            "rarity": "rare",
            "source": "crate",
            "crate": 0,
            "is_animated": false,
            "is_paintable": true,
            "bodyies": [1, 2, 3, 4, 5]
        },]

## Decal [/decals/{name}]
### Get a Decal by name [GET]

+ Response 200 (application/json)

        {
            "id": 0,
            "name": "Funny Book",
            "type": "decal",
            "rarity": "rare",
            "source": "crate",
            "crate": 0,
            "is_animated": false,
            "is_paintable": true,
            "bodyies": [1, 2, 3, 4, 5]
        }
## Decal [/decals/{id}]
### Get a Decal by id [GET]

+ Response 200 (application/json)

        {
            "id": 0,
            "name": "Funny Book",
            "type": "decal",
            "rarity": "rare",
            "source": "crate",
            "crate": 0,
            "is_animated": false,
            "is_paintable": true,
            "bodyies": [1, 2, 3, 4, 5]
        }

        
## Crates [/crates/]
### Get all Crates [GET]

+ Response 200 (application/json)

        [{
            "id": 0,
            "name": "Turbo",
            "type": "crate",
            "rarity": "rare",
            "source": "drop",
            "release_date": "2017-03-22",
            "retire_date": null,
            "items": [1, 2, 3, 4, 5]
        },]
        
## Crate [/crates/{name}]
### Get a Crate by name [GET]

+ Response 200 (application/json)

        {
            "id": 0,
            "name": "Turbo",
            "type": "crate",
            "rarity": "rare",
            "source": "drop",
            "release_date": "2017-03-22",
            "retire_date": null,
            "items": [1, 2, 3, 4, 5]
        }
## Crate [/crates/{id}]
### Get a Crate by id [GET]

+ Response 200 (application/json)

        {
            "id": 0,
            "name": "Turbo",
            "type": "crate",
            "rarity": "rare",
            "source": "drop",
            "release_date": "2017-03-22",
            "retire_date": null,
            "items": [1, 2, 3, 4, 5]
        }
## DLCs [/dlcs/]
### Get all DLC [GET]

+ Response 200 (application/json)

        [{
            "id": 0,
            "name": "Supersonic Fury",
            "type": "DLC",
            "release_date": "2015-08-13",
            "items": [1, 2, 3, 4, 5]
        },]
        
## DLC [/dlcs/{name}]
### Get a DLC by name [GET]

+ Response 200 (application/json)

        {
            "id": 0,
            "name": "Supersonic Fury",
            "type": "DLC",
            "release_date": "2015-08-13",
            "items": [1, 2, 3, 4, 5]
        }
## DLC [/dlcs/{id}]
### Get a DLC by id [GET]

+ Response 200 (application/json)

        {
            "id": 0,
            "name": "Supersonic Fury",
            "type": "DLC",
            "release_date": "2015-08-13",
            "items": [1, 2, 3, 4, 5]
        }

## ID [/id/{id}]
### Get an Object by ID [GET]

+ Response 200 (application/json)

        {
            "id": 0,
            "name": "Backfire",
            "type": "body",
            "rarity": "common",
            "source": "body",
            "release_date": "2015-07-07",
            "decals": [1, 2, 3, 4, 5]
        }

## Players [/players/]
### Get all Players [GET]

+ Response 200 (application/json)

        [{
            "id": 143045192,
            "name": "Kaydop",
            "type": "player",
            "platform": 1,
            "skill_rating": 1648,
            "wins": 5503
        },]

        
## Player [/players/{name}]
### Get a Player by name [GET]

+ Response 200 (application/json)

        {
            "id": 143045192,
            "name": "Kaydop",
            "type": "player",
            "platform": 1,
            "skill_rating": 1648,
            "wins": 5503
        }

      
## Player [/players/{id}]
### Get a Player by ID [GET]

+ Response 200 (application/json)

        {
            "id": 143045192,
            "name": "Kaydop",
            "type": "player",
            "platform": 1,
            "skill_rating": 1648,
            "wins": 5503
        }